# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-01-05 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
